### ISSUE TITLE
Which Percolator tests are reliable 

### ISSUE THREAD

**Issue by sagitter** [percolator/percolator#127]
Hi all,
tests included in ```percolator``` source archive and executed by ```ctest``` fail with 

```
+ pushd percolator
~/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator ~/rpmbuild/BUILD/percolator-percolator-4e0d58a
+ ctest -V --force-new-ctest-process
UpdateCTestConfiguration  from :/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/DartConfiguration.tcl
Test project /home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: SystemTest_Percolator_Correctness

1: Test command: /usr/bin/python "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Correctness.py"
1: Test timeout computed to be: 9.99988e+06
1: PERCOLATOR CORRECTNESS
1: - PERCOLATOR PIN XML FORMAT
1: (*) running percolator to calculate psm probabilities...
1: "/usr/bin/percolator" -k "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/data/percolator/pin/pin.xml" -X "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.pout.xml" -U 2>&1 > "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt"
1: ...TEST FAILED: percolator (psms) terminated with Unknown error 32512 exit status
1: check "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt" for details
1: Traceback (most recent call last):
1:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Correctness.py", line 75, in <module>
1:     T.doTest(canPercRunThisXml("psms","-U","percolator/pin/pin.xml"))
1:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Correctness.py", line 21, in doTest
1:     failures += 1
1: UnboundLocalError: local variable 'failures' referenced before assignment
1/4 Test #1: SystemTest_Percolator_Correctness ...***Failed    0.19 sec
test 2
    Start 2: SystemTest_Percolator_Performance

2: Test command: /usr/bin/python "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Performance.py"
2: Test timeout computed to be: 9.99988e+06
2: PERCOLATOR PERFORMANCE
2: - PERCOLATOR PIN XML FORMAT
2: (*): checking number of significant psms found...
2: Traceback (most recent call last):
2:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Performance.py", line 112, in <module>
2:     success=checkNumberOfSignificant("psms",psmFile,292) and success
2:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Performance.py", line 37, in checkNumberOfSignificant
2:     extracted = float(output[39:42])
2: TypeError: 'NoneType' object has no attribute '__getitem__'
2/4 Test #2: SystemTest_Percolator_Performance ...***Failed    0.19 sec
test 3
    Start 3: SystemTest_Qvality_Correctness

3: Test command: /usr/bin/python "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Qvality_Correctness.py"
3: Test timeout computed to be: 9.99988e+06
3: QVALITY CORRECTNESS
3: (*): running qvality...
3: "/usr/bin/qvality" "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/data/qvality/target.xcorr" "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/data/qvality/null.xcorr" > "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/qvalityOutput.txt" 2>&1
3: ...TEST FAILED: qvality terminated with 32512 exit status
3: check qvalityOutput.txt for details
3: ...TEST FAILED
3/4 Test #3: SystemTest_Qvality_Correctness ......***Failed    0.03 sec
test 4
    Start 4: SystemTest_Qvality_Performance

4: Test command: /usr/bin/python "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Qvality_Performance.py"
4: Test timeout computed to be: 9.99988e+06
4: QVALITY PERFORMANCE
4: (*): checking selected pi_0...
4: Traceback (most recent call last):
4:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Qvality_Performance.py", line 30, in <module>
4:     extracted = float(output[15:20])
4: TypeError: 'NoneType' object has no attribute '__getitem__'
4/4 Test #4: SystemTest_Qvality_Performance ......***Failed    0.18 sec

0% tests passed, 4 tests failed out of 4

Total Test time (real) =   0.58 sec

The following tests FAILED:
	  1 - SystemTest_Percolator_Correctness (Failed)
	  2 - SystemTest_Percolator_Performance (Failed)
	  3 - SystemTest_Qvality_Correctness (Failed)
	  4 - SystemTest_Qvality_Performance (Failed)
Errors while running CTest
error: Bad exit status from /var/tmp/rpm-tmp.ic3ThI (%check)
```

 but if i try to perform example as described at https://github.com/percolator/percolator/wiki/Example, ```percolator``` works fine.
Is there something wrong i have done during ```percolator``` build?

**Comment by MatthewThe** [comment]
Could you post the content of these two files:
```
/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt
/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/qvalityOutput.txt
```

**Comment by sagitter** [comment]
Respectively,

    sh: /usr/bin/percolator: No such file or directory
    sh: /usr/bin/qvality: No such file or directory

**Comment by MatthewThe** [comment]
Okay, so that just means that percolator was installed somewhere else than the testing script expected. Where do you have percolator installed (you can try the command `which percolator`, if you installed it globally)?

**Comment by sagitter** [comment]
> Okay, so that just means that percolator was installed somewhere else than the testing script expected. Where do you have percolator installed (you can try the command which percolator, if you installed it globally)?

You're right. I want that these tests are executed during building, so i had to modify the ```pathToBinaries``` variable into Python files (.py) located in all ```data/system_tests/*``` directories.

Resolved.
Thanks again.

**Comment by sagitter** [comment]
Hi.

Please, check why these tests fail:

```
+ ctest --force-new-ctest-process -V
UpdateCTestConfiguration  from :/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/DartConfiguration.tcl
Test project /home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: SystemTest_Percolator_Correctness

1: Test command: /usr/bin/python "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Correctness.py"
1: Test timeout computed to be: 9.99988e+06
1: sh: line 1: 16276 Segmentation fault      (core dumped) "/home/sagitter/rpmbuild/BUILDROOT/percolator-2.09.0-1.fc21.x86_64/usr/bin/percolator" -k "/home/sagitter/rpmbuild/BUILD/usr/share/xml/percolator/pin/pin.xml" -X "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.pout.xml" -U > "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt" 2>&1
1: PERCOLATOR CORRECTNESS
1: - PERCOLATOR PIN XML FORMAT
1: (*) running percolator to calculate psm probabilities...
1: "/home/sagitter/rpmbuild/BUILDROOT/percolator-2.09.0-1.fc21.x86_64/usr/bin/percolator" -k "/home/sagitter/rpmbuild/BUILD/usr/share/xml/percolator/pin/pin.xml" -X "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.pout.xml" -U 2>&1 > "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt"
1: ...TEST FAILED: percolator (psms) terminated with Unknown error 35584 exit status
1: check "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt" for details
1: Traceback (most recent call last):
1:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Correctness.py", line 75, in <module>
1:     T.doTest(canPercRunThisXml("psms","-U","percolator/pin/pin.xml"))
1:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Correctness.py", line 21, in doTest
1:     failures += 1
1: UnboundLocalError: local variable 'failures' referenced before assignment
1/4 Test #1: SystemTest_Percolator_Correctness ...***Failed    0.28 sec
test 2
    Start 2: SystemTest_Percolator_Performance

2: Test command: /usr/bin/python "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Performance.py"
2: Test timeout computed to be: 9.99988e+06
2: PERCOLATOR PERFORMANCE
2: - PERCOLATOR PIN XML FORMAT
2: (*): checking number of significant psms found...
2: Traceback (most recent call last):
2:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Performance.py", line 112, in <module>
2:     success=checkNumberOfSignificant("psms",psmFile,292) and success
2:   File "/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/system_tests/percolator/SystemTest_Percolator_Performance.py", line 37, in checkNumberOfSignificant
2:     extracted = float(output[39:42])
2: TypeError: 'NoneType' object has no attribute '__getitem__'
2/4 Test #2: SystemTest_Percolator_Performance ...***Failed    0.20 sec
```

```/home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.txt``` reports:

```
Percolator version 2.09, Build Date May 21 2015 21:43:16
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
/home/sagitter/rpmbuild/BUILDROOT/percolator-2.09.0-1.fc21.x86_64/usr/bin/percolator -k /home/sagitter/rpmbuild/BUILD/usr/share/xml/percolator/pin/pin.xml -X /home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.pout.xml -U
Started Thu May 21 21:45:12 2015
Hyperparameters selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
basic_ios::clear
```

**Comment by MatthewThe** [comment]
Does this file exists: `/home/sagitter/rpmbuild/BUILD/usr/share/xml/percolator/pin/pin.xml`?

If not, then it could be that `pathToData` is also pointing to the wrong place. If it does exist, could you upload the file somewhere?

**Comment by sagitter** [comment]
>then it could be that pathToData is also pointing to the wrong place

It's so. I have set ```pathToData```:

```
pushd percolator
sed -e 's|/usr/bin|%{buildroot}%{_bindir}|g' -i data/system_tests/percolator/*.py
sed -i-bak 's|\(pathToData =\).*|pathToData = "%{_builddir}/percolator-percolator-4e0d58a/data/"|g' -i data/system_tests/percolator/SystemTest_Percolator_Performance.py
sed -i.bak 's|\(pathToData =\).*|pathToData = "%{_builddir}/percolator-percolator-4e0d58a/data/"|g' -i data/system_tests/percolator/SystemTest_Percolator_Correctness.py
ctest --force-new-ctest-process -V
popd
```

```PERCOLATOR_psms.txt``` says:

```
Percolator version 2.09, Build Date May 22 2015 11:48:19
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
/home/sagitter/rpmbuild/BUILDROOT/percolator-2.09.0-1.fc21.x86_64/usr/bin/percolator -k /home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/data/percolator/pin/pin.xml -X /home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/percolator/data/PERCOLATOR_psms.pout.xml -U
Started Fri May 22 11:49:58 2015
Hyperparameters selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading XML input from datafile /home/sagitter/rpmbuild/BUILD/percolator-percolator-4e0d58a/data/percolator/pin/pin.xml
:0:0 warning: unable to open primary document entity '/usr/share/xml/percolator/xml-pin-1-3/percolator_in.xsd'
/usr/share/xml/percolator/xml-pin-1-3/percolator_in.xsd: error: unable to load
```

```/usr/share/xml/percolator/xml-pin-1-3/percolator_in.xsd``` is not installed yet because it's working in a RPM build-system.
Are tests made to be executed with all Percolator files installed ?

**Comment by MatthewThe** [comment]
Unfortunately, the current tests indeed seem to require this and I'm not sure how to remove this requirement. If you have any suggestions, they are very welcome.

**Comment by sagitter** [comment]
Don't worry; i'm already satisfied of test https://github.com/percolator/percolator/wiki/Example.
