### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: ../_decoy.psms (No such file or directory)

### ISSUE THREAD

**Issue by yvhkgdsk0** [percolator/percolator#137]
Hi,
I found a error when I used Percolator for my data.
The output is like this:
Percolator run finished; exit code: 0
Start generating new Mascot dat file with Mascot Percolator results ...
Exception in thread "main" java.io.FileNotFoundException: ../tt_decoy.psms (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at cli.Percolator2MascotDat.convert(Percolator2MascotDat.java:159)
	at cli.MascotPercolator.mascot2percolator(MascotPercolator.java:327)
	at cli.MascotPercolator.main(MascotPercolator.java:146)

Please help me with this.

**Comment by yvhkgdsk0** [comment]
there wasn't a _decoy.psms file generate and I didn't see where is wrong. How can I fix it?

**Comment by percolator** [comment]
MascotPercolator is maintained by the Sanger institute. Please contact
James Wright (cc:ed) for additional help.

Cheers
-Lukas Käll

On Wed, Aug 5, 2015 at 6:31 PM, yvhkgdsk0 <notifications@github.com> wrote:

> there wasn't a _decoy.psms file generate and I didn't see where is wrong.
> How can I fix it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percolator/percolator/issues/137#issuecomment-128061199>
> .
>



-- 
========================
Lukas Käll
http://kaell.org
Royal Institute of Technology - KTH
Science for Life Laboratory
School of Biotechnology
Box 1031, 171 65 Solna, Sweden
+46 8 52481196 or
+46 76 9425179
