### ISSUE TITLE
No such file or directory: 'msgf2pin'

### ISSUE THREAD

**Issue by rolivella** [percolator/percolator#341]
Hi, some days ago I opened an issue in the `ms2recore` repo because I got an error in execution time related to `msgf2pin`: 

https://github.com/compomics/ms2rescore/issues/78

I think that maybe the problem is in my installed `percolator` but I don't know where exactly. I installed this version: 

```bash
(venv) rolivella@hipnos3:~/mysoftware/compomics$ percolator -h
Percolator version 3.06.0, Build Date May 11 2022 12:40:18
```

Any idea? Thanks!

**Comment by percolator** [comment]
Right! You need to install a package containing msgf2pin, e.g. percolator-converters-xxx.yyy

**Comment by rolivella** [comment]
oops sorry @percolator but it's not working yet. Apparently I've installed the `msgf2pin` through the `percolator-converters-v3-06-linux-amd64.deb`. It does not work but the error is different from the previous one:  

```bash
(venv) rolivella@hipnos3:~/mysoftware/compomics$ ms2rescore -c config_default.json -m 2022MQ903_QC02_001_01_100ng.raw.mgf 2022MQ903_QC02_001_01_100ng.raw_mascot_idfilter_aaa_peptideindexer_fdr_idfilter_score.mzid
2022-09-21 15:26:48 // INFO // ms2rescore // Using MSGFPipeline.
2022-09-21 15:26:48 // INFO // ms2rescore.percolator // Running Percolator PIN converter
msgf2pin: error while loading shared libraries: libtokyocabinet.so.9: cannot open shared object file: No such file or directory
2022-09-21 15:26:48 // ERROR // ms2rescore.__main__ // Critical error occured in MS2ReScore
Traceback (most recent call last):
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/__main__.py", line 15, in main
    rescore.run()
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/__init__.py", line 233, in run
    peprec = self.pipeline.get_peprec()
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/id_file_parser.py", line 245, in get_peprec
    return self.peprec_from_pin()
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/id_file_parser.py", line 179, in peprec_from_pin
    peprec = self.original_pin.to_peptide_record(
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/id_file_parser.py", line 169, in original_pin
    self._run_percolator_converter()
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/id_file_parser.py", line 149, in _run_percolator_converter
    log_level=self.log_level,
  File "/home/rolivella/venv/lib/python3.7/site-packages/ms2rescore/percolator.py", line 532, in run_percolator_converter
    subprocess.run(command, capture_output=log_level == "debug", check=True)
  File "/home/rolivella/anaconda3/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['msgf2pin', '-P', 'XXX', '-o', '/tmp/tmpyiqe8oo3/2022MQ903_QC02_001_01_100ng.raw_mascot_idfilter_aaa_peptideindexer_fdr_idfilter_score_original.pin', '/home/rolivella/mysoftware/compomics/2022MQ903_QC02_001_01_100ng.raw_mascot_idfilter_aaa_peptideindexer_fdr_idfilter_score.mzid']' returned non-zero exit status 127.
```

Am I missing this lib `libtokyocabinet.so.9`? Thanks!

**Comment by MatthewThe** [comment]
Yes, the problem is that the library `libtokyocabinet.so.9` is missing.
You can install it with `sudo apt-get install -y libtokyocabinet-dev`.
